# Generated by Django 2.2 on 2019-09-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190816_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_reg',
        ),
    ]
