# Generated by Django 2.2 on 2019-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
