# Generated by Django 2.2 on 2019-09-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_auto_20190915_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_detail',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product'),
        ),
    ]
